server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/Users/pc/microservice/javatab-microservice/config-server/src/main/resources/config/licensingservice